# 服务器相关配置
server:
  port: 8989
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
# spring相关配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  mvc:
    view:
      suffix: .jsp
      prefix: /
  redis:
        host: 192.168.79.137
        port: 6379
        database: 0
# mybatis相关配置
mybatis:
  type-aliases-package: com.xc.entity
  mapper-locations: classpath:com/xc/mapper/*.xml
# 日志
logging:
  level:
    com.xc.dao: debug
